config/routes.rb
Rails.application.routes.draw do
  
  
  # # Dapatin delete method melalui ajax
  # resources :articles do
  #   get "delete"
  #   collection { post :import }
  # end 

  # ROUTE STANDARD

  # get 'articles/edit', to: "articles#edit", as: :articles
  # ------------------------------------------------------

  # get "sign_up" => "users#new", :as => "sign_up"
  # get "login" => "session#new", :as => "login"
  resources :projects
  resources :sessions, only: [:update]

  root to: 'pages#index'

  # RESTFULL ROUTE
  # root :to => "articles#index" 
  # resources :articles

  # resources :comments
   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :load_projects, only: :index
  load_and_authorize_resource
  
  def index
    @projects = Project.all
    authorize! :index, @project
  end

  def new
    @project = Project.new
    authorize! :new, @project
  end
  
  def show
    @project = Project.find(params[:id])
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:success] = 'Project Tersimpan!'
      redirect_to root_path
    else
      flash[:error] = "Gagal disimpan"
      render 'new'
    end
   
    authorize! :create, @project
  end

  def edit
  @project = Project.find(params[:id])
  authorize! :edit, @project
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      flash[:success] = 'Project was updated!'
      redirect_to root_path
    else
      render 'edit'
    end
    authorize! :update, @project
  end

  def import
    Article.import(params[:file])
    redirect_to root_url, notice: "Articles imported"
  end

  def destroy
    @project = Project.find(params[:id])
    if @project.destroy
      flash[:success] = 'Project was destroyed!'
    else
      flash[:warning] = 'Cannot destroy this project...'
    end
    redirect_to root_path
    authorize! :destroy, @project
  end

  private

  def project_params
    params.require(:project).permit(:title,  :ongoing, :content)
  end

  def load_projects
    @projects = Project.accessible_by(current_ability).order('created_at DESC')
  end
end

app/views/projects/_form.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <%= form_for @project, remote: true, html: { style: "display:inline;" } do |f| %>
      <div class="modal-body">
        <ul class="errors"></ul>

        
        <div class="form-group">
          <%= f.label :title, class:"control-label" %>
          <%= f.text_field :title, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :content, class: "control-label" %>
          <%= f.text_area :content, cols: 20, rows: 10 , class: "form-control" %>
        </div>
      </div>
      <div class="modal-footer">
        <%= f.submit class: "btn btn-primary" %>
        <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/destroy.html.erb
<h1>Projects#destroy</h1>
<p>Find me in app/views/projects/destroy.html.erb</p>

app/views/projects/edit.html.erb
<div class="page-header"><h1>Edit Project</h1></div>

<%= render 'form' %>

app/views/projects/index.html.erb
<div class="page-header mb-4"><h1>Projects</h1></div>
<div class="container-fluid">
  
  <p id="notice"><%= notice %></p>

  <table id="projects" class="display" data-source="<%= projects_url(format: "json") %>">
    <thead>
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
      </tr>
    </thead>

    <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= project.title %></td>
          <td><%= project.content %></td>
          <td><%= link_to 'Show', project %></td>
          <td><%= link_to 'Edit', edit_project_path(project) %></td>
          <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Project', new_project_path %>
  <div id="article-modal" class="modal fade"></div>
</div>

app/views/projects/new.html.erb
<div class="page-header"><h1>New Project</h1></div>

<%= render 'form' %>

app/views/projects/show.html.erb
<h5><%= @project.title %></h5>
<p><%= @project.content %></p>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>